// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React                   = require("react");
var ReasonReact             = require("reason-react/lib/js/src/ReasonReact.js");
var Utils$ReactParcelSample = require("../../../utils.bs.js");

var component = ReasonReact.statelessComponent("Modal");

function make(_, _$1) {
  var myLabel = React.cloneElement(React.createElement("span", undefined), {
        "aria-hidden": "true"
      }, Utils$ReactParcelSample.str("&times;"));
  var myButton = React.cloneElement(React.createElement("button", {
            className: "close",
            type: "button"
          }), {
        "data-dismiss": "modal",
        "aria-label": "Close"
      }, myLabel);
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.cloneElement(React.createElement("div", {
                      className: "modal modal-dialog-centered",
                      id: "exampleModal",
                      role: "dialog"
                    }), {
                  tabIndex: "-1",
                  "aria-hidden": "true"
                }, React.createElement("div", {
                      className: "modal-dialog",
                      role: "document"
                    }, React.createElement("div", {
                          className: "modal-content"
                        }, React.createElement("div", {
                              className: "modal-header"
                            }, React.createElement("h5", {
                                  className: "modal-title"
                                }, Utils$ReactParcelSample.str("Modal title")), myButton), React.createElement("div", {
                              className: "modal-body"
                            }, React.createElement("p", undefined, Utils$ReactParcelSample.str("Modal body text goes here."))), React.createElement("div", {
                              className: "modal-footer"
                            }, React.createElement("button", {
                                  className: "btn btn-primary",
                                  type: "button"
                                }, Utils$ReactParcelSample.str("Save changes")), React.cloneElement(React.createElement("button", {
                                      className: "btn btn-secondary",
                                      type: "button"
                                    }), {
                                  "data-dismiss": "modal"
                                }, Utils$ReactParcelSample.str("Close"))))));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
