// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React                   = require("react");
var ReasonReact             = require("reason-react/lib/js/src/ReasonReact.js");
var Utils$ReactParcelSample = require("../../../utils.bs.js");

var component = ReasonReact.statelessComponent("TodoButton");

function renderIcon(iconName) {
  if (iconName) {
    return React.createElement("i", {
                className: "fa fa-" + (String(iconName[0]) + " pr-2")
              });
  } else {
    return null;
  }
}

function make(iconName, $staropt$star, label, onClick, _) {
  var className = $staropt$star ? $staropt$star[0] : "btn btn-primary";
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("button", {
                  className: className,
                  onClick: onClick
                }, renderIcon(iconName), Utils$ReactParcelSample.str(label));
    });
  return newrecord;
}

exports.component  = component;
exports.renderIcon = renderIcon;
exports.make       = make;
/* component Not a pure module */
