// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("TodoInput");

function make(value, onChange, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("input", {
                  type: "text",
                  value: value,
                  onChange: onChange
                });
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
