// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe             = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact            = require("reason-react/lib/js/src/ReasonReact.js");
var Root$ReactParcelSample = require("./components/Root/Root.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Root$ReactParcelSample.make(/* array */[])), "root");

/*  Not a pure module */
