// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React                    = require("react");
var ReasonReact              = require("reason-react/lib/js/src/ReasonReact.js");
var Materialui$ReactTemplate = require("../bindings/materialui.bs.js");

var component = ReasonReact.statelessComponent("Header");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Materialui$ReactTemplate.AppBar[/* make */1](/* None */0, /* None */0, /* None */0, /* array */[React.createElement("div", undefined, "huhu")]));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
