// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block                    = require("bs-platform/lib/js/block.js");
var ReasonReact              = require("reason-react/lib/js/src/ReasonReact.js");
var Materialui$ReactTemplate = require("../bindings/materialui.bs.js");

var initialState = /* record */[/* expanded : true */1];

var component = ReasonReact.reducerComponent("Root");

function handleClick(_, _$1) {
  console.log("clicked!");
  return /* () */0;
}

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Materialui$ReactTemplate.AppBar[/* make */1](/* None */0, /* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Materialui$ReactTemplate.Toolbar[/* make */0](/* None */0, /* array */[
                                ReasonReact.element(/* None */0, /* None */0, Materialui$ReactTemplate.IconButton[/* make */0](/* None */0, /* Some */["contrast"], /* None */0, /* None */0, /* None */0, /* Some */["Menu"], /* array */["face"])),
                                ReasonReact.element(/* None */0, /* None */0, Materialui$ReactTemplate.Button[/* make */0](/* Some */[/* true */1], /* None */0, /* None */0, /* None */0, /* array */["Click"]))
                              ]))]));
    });
  newrecord[/* initialState */10] = (function () {
      return initialState;
    });
  newrecord[/* reducer */12] = (function (action, _) {
      if (action !== 0) {
        return /* Update */Block.__(0, [/* record */[/* expanded : false */0]]);
      } else {
        return /* Update */Block.__(0, [/* record */[/* expanded : true */1]]);
      }
    });
  return newrecord;
}

exports.initialState = initialState;
exports.component    = component;
exports.handleClick  = handleClick;
exports.make         = make;
/* component Not a pure module */
