// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MaterialUi  = require("material-ui");

function make(_, _$1, $staropt$star, children) {
  var onExpandChange = $staropt$star ? $staropt$star[0] : (function () {
        return /* () */0;
      });
  return ReasonReact.wrapJsForReason(MaterialUi.Card, {
              onExpandChange: (function (newExpandedState) {
                  return Curry._1(onExpandChange, +newExpandedState);
                })
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
